### ISSUE TITLE
Replace Osicat dependency used for `gettid` on Linux?

### ISSUE THREAD

**Issue by vindarel** [ruricolist/moira#1]
Hi,

Moira depends on Osicat which makes it a bit harder to deploy executables by its dependency on `libosicat.so`.

Osicat is used to get a thread id, a syscall with `sys-gettid` equal to 186.
It *seems* we are not far from a `defcfun` away.

Would you accept to replace osicat by a FFI call?

(edit)

> On Linux only, Moira also tracks the thread ID (value of gettid) of the Lisp threads it launches. This can be useful for tracking the resource usage of individual threads.

Or osicat and this feature could be an optional install parameter.

(*I'm not much impacted and might give a try eventually; I might need guidance*)

**Comment by ruricolist** [comment]
My first suggestion would be moving the Osicat dependency into an optionally loaded subsystem (moira/linux).

Syscall numbers in Linux are stable, but they differ by architecture: see https://chromium.googlesource.com/chromiumos/docs/+/HEAD/constants/syscalls.md#cross_arch-numbers.
